name: setup

runs:
  using: "composite"
  steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/Hydrogen'
      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
        shell: bash
