name: setup

runs:
  using: "composite"
  steps:
      - name: Checkout code
        uses: actions/checkout@v3
          submodules: recursive
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/Hydrogen'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
