name: setup

runs:
  using: "composite"
  steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/Hydrogen'
      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --ignore-scripts
        shell: bash
        if: steps.npm-cache.outputs.cache-hit != 'true'
