name: setup

runs:
  using: "composite"
  steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/Hydrogen'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --ignore-scripts
        shell: 'bash'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
