[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
solc = '0.8.18'

[fuzz]
runs = 10_000
depth = 10

# Extreme Fuzzing CI Profile
[profile.ci]
runs = 10_000
depth = 100
